stages:
  - test

test_mobile:
  stage: test
  image: maven:3.9.3-openjdk-17
  script:  
    - ./browserstack-local --key $BROWSERSTACK_KEY --daemon start
    - mvn clean test -DsuiteXmlFile=testng.xml
    - ./browserstack-local --key $BROWSERSTACK_KEY --daemon stop
  tags:
    - docker
artifacts:
// meme si a Ã©choue
    when: always
    paths:
      - [cite_start]target/surefire-reports/
